name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: --cwd install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: --cwd test # will run `yarn test` command
